apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      component: greeting
  template:
    metadata:
      labels:
        app: flask-app
        component: greeting
    spec:
      containers:
      - name: flask-app
        image: 380544824653.dkr.ecr.us-east-1.amazonaws.com/mkhan-midterm-repo:app
        ports:
        - containerPort: 5000