apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: flask-app
    component: greeting