apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app
    component: greeting